#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh
source $(dirname $0)/utils.sh

# for jq
PATH=/usr/local/bin:$PATH

payload=$TMPDIR/pipeline-discovery-resource-request

cat > $payload <&0

input_version=$(jq -r '.version.ref' < "$payload")

destination=$TMPDIR/git-shorthash-resource
mkdir -p $destination
prepare_repository "$destination" "$payload" > "$destination/shorthash"

# return latest tag on this branch
#version=$(jq -r '.version.ref // ""' < "$payload")
#tags=$(git tag --merged "$branch" -l --sort=version:refname "*" 2>/dev/null)
shorthash="$(cat "$destination/shorthash")"

#jq -n "[{ref: \"$shorthash\"}]" >&3

if [ "$input_version" == "$shorthash" ]; then
  jq -n "[{}]" >&3
else
  jq -n "[{ref: \"$input_version\"}, {ref: \"$shorthash\"}]" >&3
fi
