#!/bin/bash

set -e

docker build --tag shorthash .
docker run --rm -v `pwd`/assets:/opt/resource -v /tmp:/black shorthash "echo '{ \"source\": {\"uri\": \"https://github.com/tekn0ir/concourse-git-shorthash-resource.git\"} }' | /opt/resource/in black"


#git ls-remote https://github.com/tekn0ir/concourse-git-shorthash-resource.git  | grep HEAD | awk '{ print $1}' | cut -c 1-7
